fuzzyWuzzy: main.o fuzzyFind.o fuzzyKnow.o fuzzyThink.o
	 gcc -o fuzzyWuzzy main.o fuzzyFind.o fuzzyKnow.o fuzzyThink.o

main.o:	main.c
		gcc -c main.c

fuzzyFind.o:	fuzzyFind.c
		gcc -c fuzzyFind.c

fuzzyKnow.o:	fuzzyKnow.c
		gcc -c fuzzyKnow.c

fuzzyThink.o:	fuzzyThink.c
		gcc -c fuzzyThink.c
